### ISSUE TITLE
报错但不影响使用

### ISSUE THREAD

**Issue by GBStudios** [Fireflyest/Activity#1]
[19:55:31 ERROR]: [CraftGUI] Unhandled exception occurred in onPacketSending(PacketEvent) for CraftGUI
java.lang.IndexOutOfBoundsException: Index: 54, Size: 46
        at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:756) ~[?:?]
        at java.util.ArrayList.listIterator(ArrayList.java:923) ~[?:?]
        at org.fireflyest.craftgui.protocol.ViewProtocol$1.onPacketSending(ViewProtocol.java:87) ~[CraftGUI-1.1.6.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:547) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:521) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketSending(NetworkManagerInjector.java:99) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processOutbound(NettyChannelInjector.java:571) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector$2.doProxyRunnable(NettyChannelInjector.java:472) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.proxyRunnable(NettyEventLoopProxy.java:43) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:252) ~[ProtocolLib.jar:?]
        at net.minecraft.network.Connection.sendPacket(Connection.java:433) ~[?:?]
        at net.minecraft.network.Connection.send(Connection.java:380) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2165) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.send(ServerGamePacketListenerImpl.java:2151) ~[?:?]
        at net.minecraft.server.level.ServerPlayer$1.sendInitialData(ServerPlayer.java:282) ~[?:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.sendAllDataToRemote(AbstractContainerMenu.java:201) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftPlayer.updateInventory(CraftPlayer.java:1386) ~[paper-1.19.2.jar:git-Paper-304]
        at me.arasple.mc.trmenu.module.display.MenuSession.close(MenuSession.kt:167) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.module.internal.listener.ListenerBukkitInventory.e(ListenerBukkitInventory.kt:22) ~[TrMenu-3.1.17.jar:?]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:731) ~[?:?]
        at me.arasple.mc.trmenu.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus.invoke(EventBus.kt:132) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus.invoke$default(EventBus.kt:130) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:77) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.event.EventBus$registerBukkit$2.invoke(EventBus.kt:76) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.common.platform.function.ListenerKt$registerBukkitListener$1.invoke(Listener.kt:21) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$registerListener$listener$1.invoke(BukkitListener.kt:35) ~[TrMenu-3.1.17.jar:?]
        at me.arasple.mc.trmenu.taboolib.platform.BukkitListener$BukkitListener.execute(BukkitListener.kt:72) ~[TrMenu-3.1.17.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-304]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1357) ~[paper-1.19.2.jar:git-Paper-304]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1343) ~[paper-1.19.2.jar:git-Paper-304]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftHumanEntity.openCustomInventory(CraftHumanEntity.java:354) ~[paper-1.19.2.jar:git-Paper-304]
        at org.bukkit.craftbukkit.v1_19_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:339) ~[paper-1.19.2.jar:git-Paper-304]
        at org.fireflyest.craftgui.core.ViewGuideImpl.openView(ViewGuideImpl.java:183) ~[CraftGUI-1.1.6.jar:?]
        at com.fireflyest.activity.command.ActivityCommand.executeCommand(ActivityCommand.java:58) ~[Activity-3.0.2.jar:?]
        at com.fireflyest.activity.command.ActivityCommand.onCommand(ActivityCommand.java:49) ~[Activity-3.0.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:916) ~[paper-1.19.2.jar:git-Paper-304]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-304]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2294) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2248) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-304]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-304]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-304]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-304]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-304]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-304]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-304]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-304]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:55:31 ERROR]: Parameters: 
  net.minecraft.network.protocol.game.PacketPlayOutWindowItems@1d98ba23[
    a=0
    b=1235
    c=[1 air, 1 air, 1 air, 1 air, 1 air, 1 netherite_helmet, 1 elytra, 1 netherite_leggings, 1 netherite_boots, 1 pink_shulker_box, 19 glass, 20 cut_sandstone, 5 white_wool, 64 nether_brick_slab, 32 nether_brick_slab, 64 nether_bricks, 16 nether_bricks, 5 cracked_nether_bricks, 24 torch, 1 crafting_table, 37 glass_pane, 16 white_carpet, 3 soul_campfire, 4 hopper, 64 oak_trapdoor, 44 oak_trapdoor, 5 stick, 1 water_bucket, 32 cod, 33 arrow, 1 air, 1 air, 1 air, 1 air, 1 air, 1 air, 1 diamond_sword, 1 bow, 1 diamond_pickaxe, 1 diamond_axe, 1 diamond_shovel, 60 golden_carrot, 19 firework_rocket, 1 air, 1 air, 1 air]
    d=1 air
  ]

**Comment by GBStudios** [comment]
服务器 版本: 1.19.2 Paper
